### ISSUE TITLE
Information for using IPS 

### ISSUE THREAD

**Issue by Xerodius** [StamusNetworks/SELKS#195]
Hello, I have some questions regarding using Suricata in IPS Mode.
If I understand correctly, if I want to use Suricata with reject commands, then the default configuration(first time setup script) is sufficient, but if I want to use Drop rules then I have to set up in IPS mode.

I followed the guide here: https://github.com/StamusNetworks/SELKS/wiki/Initial-Setup---Suricata-IPS

My setup is currently on a local VM, but soon it's going to be migrated on an dedicated Server, and the goal is for Suricata to be used as a Gateway between the office LAN and the Internet.

From VMware I have setup 3 network adapters, and my config files are as follows:

In  `/etc/suricata/selks5-addin.yaml`
 
I added the following code

```
af-packet:
 - interface: ens37
   threads: 1 # or a number that is below half the number of cores available
   defrag: no
   cluster-type: cluster_flow
   cluster-id: 98
   copy-mode: ips
   copy-iface: ens38
   tpacket-v3: no
   ring-size: 2048
   use-mmap: yes

 - interface: ens38
   threads: 1 # or a number that is below half the number of cores available
   cluster-id: 97
   defrag: no
   cluster-type: cluster_flow
   copy-mode: ips
   copy-iface: ens37
   tpacket-v3: no
   ring-size: 2048
   use-mmap: yes
```
Also in `/etc/network/interfaces` :

```
# The primary network interface
allow-hotplug ens33
iface ens33 inet dhcp

iface ens37 inet manual
     pre-up ifconfig $IFACE up
     post-down ifconfig $IFACE down
     post-up /etc/network/if-up.d/selks-idps-interface-tuneup_stamus

iface ens38 inet manual
     pre-up ifconfig $IFACE up
     post-down ifconfig $IFACE down
     post-up /etc/network/if-up.d/selks-idps-interface-tuneup_stamus
```

Another fact is, that If I try to set up Suricata using NFQUEUE(with the instructions provided on Suricata's page) the DROP rules are working, however in my current setup nothing is logged.
If I remove the above setup, and just have an Interface and Suricata in IDPS mode(the default one) everything is working fine, and the reject rules seem to work.

Finally, in order to test my setup I use either a curl command or a custom ping rule:
`curl -A "Black^Cn" www.google.com`

`drop icmp any any <> any any (msg:"Trying to drop ICMP traffic"; classtype:policy-violation; sid:765765121; rev:1;)`
